### ISSUE TITLE
Worth adding in the application owner where it exists

### ISSUE THREAD

**Issue by turnma** [microsoft/AzureADGraphApps#11]
This could be improved by extracting the owner at lines 105/150
	
	$ownerUPN = (Get-AzureADServicePrincipalOwner -ObjectId $client.ObjectId).UserPrincipalName

and then updating the two New-Object PSObject calls to add
			"Owner" = $ownerUPN

**Comment by merill** [comment]
Thanks @turnma for the suggestion!
