### ISSUE TITLE
Is Cloud Shell (Azure Portal PowerShell) supported?

### ISSUE THREAD

**Issue by jbm00n** [microsoft/AzureADGraphApps#6]
Hello,

I tried to run the script in Cloud Shell and got a bunch of exceptions.

> import-Module: /home/jm/tmp/Get-AzureADGraphApps.ps1:23
Line |
  23 |              Import-Module $m
     |              ~~~~~~~~~~~~~~~~
     | Assembly with same name is already loaded

> InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:60
Line |
  60 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a
     | CommandInfo object.

> InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:174
Line |
 174 |              $envName = $script:CloudEnvironmentMap[$env:ACC_CLOUD]
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.

> Get-AzureADServicePrincipal: /home/jm/tmp/Get-AzureADGraphApps.ps1:75
Line |
  75 |      $servicePrincipals = Get-AzureADServicePrincipal -All $true
     |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You must call the Connect-AzureAD cmdlet before calling any other cmdlets.

> InvalidOperation: /home/jm/tmp/Get-AzureADGraphApps.ps1:136
Line |
 136 |      $script:ObjectByObjectClassId['ServicePrincipal'].GetEnumerator() …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

**Comment by pacroy** [comment]
I'm getting the same issue. The script does not run on Cloud Shell nor Mac using PowerShell Core. 😢

**Comment by dhruvchand** [comment]
Hey @pacroy and @jbm00n, unfortunately this script is primarily intended at administrators who are likely to use the full fledged PowerShell Desktop edition on a Windows machine, as a convenience script. I merged a PR earlier today that makes that check explicit.

I also updated the README with an alternative that allows you to fetch the same list, but through the Azure portal:
https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-faq#method-2-use-the-app-registrations-menu-of-the-azure-portal

a. Go to the Azure portal at https://portal.azure.com and select Azure Active Directory.
c. From the Azure Active Directory side-menu, select App registrations.
d. Go to All Applications tab, click Add filters option and choose Requested API > Apply
e. Choose ‘Microsoft APIs’ in next window and select ‘Azure Active Directory Graph’ > Apply

You should see a list applications that have requested Azure Active Directory Graph permissions (and therefore have it as a dependency. )

Our apologies for the inconvenience.
