### ISSUE TITLE
CSV file not generated correctly - header mismatch?

### ISSUE THREAD

**Issue by HenrikBernhard** [microsoft/AzureADGraphApps#9]
If i call as instructed 
`.\Get-AzureADGraphApps.ps1 | Export-Csv .\aadgraphapps.csv -NoTypeInformation`
the output csv does not contain the data i would expect. 

Somehow the array generated has two different types of objects. So calling line 0 or 1 has different headers - causing only the first line to go correctly into the csv, with rest of lines being blank as columns have different names

```
$apps = .\Get-AzureADGraphApps.ps1

$apps[0]
Account      :  <removed>
Environment  : AzureCloud
Tenant       : <removed>
TenantId     : <removed>
TenantDomain : <removed>


$apps[1]
ObjectId       : <removed>
DisplayName    : <removed>
ApplicationId  : <removed>
PermissionType : Delegated-AllPrincipals
Resource       : Windows Azure Active Directory
Permission     : User.Read
MicrosoftApp   : False

```
To get the right data out i just grabbed from line 1 with
$apps[01..3000] | Export-Csv .\aadgraphapps.csv -NoTypeInformation

**Comment by jsmartbnl** [comment]
Can confirm.  
Connect-AzureAD on line 173 is sending an object to the pipeline.
Piping that object to Out-Null will work, or even just pulling Connect-AzureAD out of the script itself and putting it in the usage section would do the trick.

**Comment by Wittionary** [comment]
Thanks, y'all! I'm glad I came across this issue because I thought the output was suspicious, but already sent the "all clear" to the team.
If we can get MS involved in the issue, perhaps we can get a PR merged.

**Comment by jsmartbnl** [comment]
I'd love to help, but it's been years and I haven't gotten the OK from my work's legal group to sign the CUA. :/

**Comment by dhruvchand** [comment]
Great catch, thanks everyone. I merged a PR to pipe Connect-AzureAD to null
